name: "Hello!"

on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  Example:
    runs-on: ${{ matrix.host }}
    defaults:
      run:
        shell: bash
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix: 
        host: [windows-latest, ubuntu-latest, macos-latest]
        cpu: ['']
        os: ['']
        include:
            - {host: 'macos-latest',   cpu: x86_64,   os: win64}
            - {host: 'ubuntu-latest',  cpu: i386,     os: win32}
            - {host: 'ubuntu-latest',  cpu: x86_64,   os: win64}
            - {host: 'windows-latest', cpu: aarch64,  os: linux}
            - {host: 'windows-latest', cpu: powerpc,  os: linux}
            - {host: 'windows-latest', cpu: x86_64,   os: linux}
            - {host: 'windows-latest', cpu: x86_64,   os: win64}
            #
            # Also working:
            #
            # {host: 'ubuntu-latest',  cpu: arm,      os: wince}
            # {host: 'ubuntu-latest',  cpu: i386,     os: linux}
            # {host: 'ubuntu-latest',  cpu: i386,     os: nativent}
            # {host: 'ubuntu-latest',  cpu: i386,     os: wince}
            # {host: 'windows-latest', cpu: arm,      os: linux}
            # {host: 'windows-latest', cpu: arm,      os: wince}
            # {host: 'windows-latest', cpu: i386,     os: freebsd}
            # {host: 'windows-latest', cpu: i386,     os: go32v2}
            # {host: 'windows-latest', cpu: i386,     os: linux}
            # {host: 'windows-latest', cpu: i386,     os: nativent}
            # {host: 'windows-latest', cpu: i386,     os: wince}
            # {host: 'windows-latest', cpu: mips,     os: linux}
            # {host: 'windows-latest', cpu: mipsel,   os: linux}
            # {host: 'windows-latest', cpu: powerpc64,os: linux}
            # {host: 'windows-latest', cpu: sparc,    os: linux}
            # {host: 'windows-latest', cpu: sparc64,  os: linux}
            # {host: 'windows-latest', cpu: x86_64,   os: freebsd}
            #
            # Failed compilations:
            #
            # {host: 'macos-latest',   cpu: aarch64,  os: darwin}   Error: ppca64 can't be executed, error message: Failed to execute "ppca64", error code: 127
            # {host: 'macos-latest',   cpu: aarch64,  os: ios}      Error: ppca64 can't be executed, error message: Failed to execute "ppca64", error code: 127
            # {host: 'macos-latest',   cpu: arm,      os: wince}    Error: ppcarm can't be executed, error message: Failed to execute "ppcarm", error code: 127
            # {host: 'macos-latest',   cpu: i386,     os: embedded} Error: ppc386 can't be executed, error message: Failed to execute "ppc386", error code: 127
            # {host: 'macos-latest',   cpu: i386,     os: nativent} Error: ppc386 can't be executed, error message: Failed to execute "ppc386", error code: 127
            # {host: 'macos-latest',   cpu: i386,     os: win32}    Error: ppc386 can't be executed, error message: Failed to execute "ppc386", error code: 127
            # {host: 'macos-latest',   cpu: i386,     os: wince}    Error: ppc386 can't be executed, error message: Failed to execute "ppc386", error code: 127
            # {host: 'macos-latest',   cpu: i8086,    os: embedded} Error: ppc8086 can't be executed, error message: Failed to execute "ppc8086", error code: 127
            # {host: 'ubuntu-latest',  cpu: i386,     os: embedded} hello.pas(3,1) Error: Util i386-embedded-ld not found, switching to external linking
            # {host: 'ubuntu-latest',  cpu: i8086,    os: embedded} Fatal: Can't find unit system used by Program
            # {host: 'ubuntu-latest',  cpu: x86_64,   os: embedded} hello.pas(3,1) Error: Util x86_64-embedded-ld not found, switching to external linking
            # {host: 'windows-latest', cpu: avr,      os: embedded} D:\a\hello-fpc\hello-fpc\.fpc\installed\bin\i386-win32\avr-embedded-ld.exe: cannot find .\.fpc\installed\units\avr-embedded\rtl\system.o
            # {host: 'windows-latest', cpu: i386,     os: embedded} hello.pas(3,1) Error: Util i386-embedded-ld.exe not found, switching to external linking
            # {host: 'windows-latest', cpu: i8086,    os: embedded} Fatal: Can't find unit system used by Program
            # {host: 'windows-latest', cpu: x86_64,   os: embedded} hello.pas(3,1) Error: Util x86_64-embedded-ld.exe not found, switching to external linking

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup FPC
        uses: visualdoj/setup-fpc@main
        with:
            cross: "${{ matrix.cpu }}${{ matrix.os != '' && '-' || '' }}${{ matrix.os }}"

      - name: Print FPC version
        run: fpc -i

      - name: Compile
        if: matrix.os == ''
        run: fpc hello.pas

      - name: Test
        if: matrix.os == ''
        shell: bash
        run: "./hello"

      - name: Compile to another platform
        if: matrix.os != ''
        run: fpc -P${{ matrix.cpu }} -T${{ matrix.os }} hello.pas

      - name: Install virtual machine
        if: matrix.os != '' && runner.os == 'Linux'
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Show available platforms
        if: matrix.os != '' && runner.os == 'Linux'
        run: echo ${{ steps.qemu.outputs.platforms }}
